config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  attachment :profile_image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    user_path(resource)
  end 
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="col-md-3">
  <!--User info開始-->
  <h2>User info</h2>
  <div class="profile-container">
    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
    <table class="table">
      <tbody><tr></tr>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to user.follower.count, following_user_path(user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followed.count, followers_user_path(user) %></th>
        </tr>
      </tbody></table>
    </table>
    <div class="row">
      <% if current_user == user %>
        <a class="btn btn-outline-secondary btn-block fas fa-user-cog" href="/users/<%= @user.id %>/edit"></a>
      <% else %>
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, :class=>"btn btn-info" %>
        <% else %>
          <%= link_to 'フォローする', follow_path(user.id), method: :POST, :class=>"btn btn-success" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <!--User info終了-->
  <!--New book開始-->
  <h2 class="mt-3">New book</h2>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form_with model: @book, local:true do |f| %>
      <h6>Title</h6>
      <%= f.text_field :title %>
      <h6>Opinion</h6>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book', :class=>"btn btn-success" %>
    <% end %>
  </div>
  <!--New book終了-->
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User Info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <h6>Name</h6>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <h6>Image</h6>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <h6>Introduction</h6>
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', :class=>"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
  <h2>Follower Users</h2>
  <% if @user.followed.count == 0 %>
    <div class="w-100">ユーザはいません</div>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @user.follower_user.each do |user|  %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
            <td><%= user.name %></td>
            <td>フォロー数： <%= user.follower.count %></td>
            <td>フォロワー数：<%= user.followed.count %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  </div>
</div>

app/views/users/following.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
  <h2>Follow Users</h2>
  <% if @user.follower.count == 0 %>
    <div class="w-100">ユーザはいません</div>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @user.following_user.each do |user|  %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
            <td><%= user.name %></td>
            <td>フォロー数： <%= user.follower.count %></td>
            <td>フォロワー数：<%= user.followed.count %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--User info、New book開始-->
    <%= render 'users/list', user: @user %>
    <!--User info、New book終了-->
    <!--Users開始-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
              <td><%= user.name %></td>
              <td>フォロー数： <%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>
              <td>
              <% if current_user != user %>
                <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                <% end %>
              <% end %>
              </td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!--Users終了-->
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--User info、New book開始-->
    <%= render 'users/list', user: @user %>
    <!--User info、New book終了-->
    <!--UserBooks開始-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to attachment_image_tag(book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60"), "/users/#{book.user.id}" %></td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!--UserBooks終了-->
  </div>
</div>